-   id: jsonlint
    name: jsonlint
    entry: jsonlint
    language: node
    'files': json
    args: ["--quiet", "--compact"]
    require_serial: false
    additional_dependencies: ["jsonlint@1.4.1"]
